export const flightMasters = [
   {
    key: "PUSGUM_LJ531_532",
    rawKey: "PUSGUM_LJ531/2",
    origin: "PUS",
    destination: "GUM",
    route: "PUS-GUM",
    airline: "LJ",
    depFlight: "LJ531",
    retFlight: "LJ532",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },   
{
    key: "ICNGUM_LJ917_918",
    rawKey: "ICNGUM_LJ917/8",
    origin: "ICN",
    destination: "GUM",
    route: "ICN-GUM",
    airline: "LJ",
    depFlight: "LJ917",
    retFlight: "LJ918",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
{
    key: "ICNGUM_LJ917_916",
    rawKey: "ICNGUM_LJ917/6",
    origin: "ICN",
    destination: "GUM",
    route: "ICN-GUM",
    airline: "LJ",
    depFlight: "LJ917",
    retFlight: "LJ917",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  }, 
{
    key: "ICNGUM_LJ915_918",
    rawKey: "ICNGUM_LJ915/8",
    origin: "ICN",
    destination: "GUM",
    route: "ICN-GUM",
    airline: "LJ",
    depFlight: "LJ915",
    retFlight: "LJ918",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
{
    key: "ICNGUM_LJ915_916",
    rawKey: "ICNGUM_LJ915/6",
    origin: "ICN",
    destination: "GUM",
    route: "ICN-GUM",
    airline: "LJ",
    depFlight: "LJ915",
    retFlight: "LJ916",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
 {
    key: "ICNDAD_LJ081_082",
    rawKey: "ICNDAD_LJ081/2",
    origin: "ICN",
    destination: "DAD",
    route: "ICN-DAD_PM",
    airline: "LJ",
    depFlight: "LJ081",
    retFlight: "LJ082",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNDAD_7C2217_2218",
    rawKey: "ICNDAD_7C2217/8",
    origin: "ICN",
    destination: "DAD",
    route: "ICN-DAD_PM",
    airline: "7C",
    depFlight: "7C2217",
    retFlight: "7C2218",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNDAD_ZE593_594",
    rawKey: "ICNDAD_ZE593/4",
    origin: "ICN",
    destination: "DAD",
    route: "ICN-DAD_PM",
    airline: "ZE",
    depFlight: "ZE593",
    retFlight: "ZE594",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNDAD_TW013_014",
    rawKey: "ICNDAD_TW013/4",
    origin: "ICN",
    destination: "DAD",
    route: "ICN-DAD_PM",
    airline: "TW",
    depFlight: "TW013",
    retFlight: "TW014",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNCXR_TW033_034",
    rawKey: "ICNCXR_TW033/4",
    origin: "ICN",
    destination: "CXR",
    route: "ICN-CXR",
    airline: "TW",
    depFlight: "TW033",
    retFlight: "TW034",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNCXR_LJ087_088",
    rawKey: "ICNCXR_LJ087/8",
    origin: "ICN",
    destination: "CXR",
    route: "ICN-CXR",
    airline: "LJ",
    depFlight: "LJ087",
    retFlight: "LJ088",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNCXR_ZE561_562",
    rawKey: "ICNCXR_ZE561/2",
    origin: "ICN",
    destination: "CXR",
    route: "ICN-CXR",
    airline: "ZE",
    depFlight: "ZE561",
    retFlight: "ZE562",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNCXR_7C2303_2304",
    rawKey: "ICNCXR_7C2303/4",
    origin: "ICN",
    destination: "CXR",
    route: "ICN-CXR",
    airline: "7C",
    depFlight: "7C2303",
    retFlight: "7C2304",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNPQC_LJ091_092",
    rawKey: "ICNPQC_LJ091/2",
    origin: "ICN",
    destination: "PQC",
    route: "ICN-PQC",
    airline: "LJ",
    depFlight: "LJ091",
    retFlight: "LJ092",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNPQC_7C2315_2316",
    rawKey: "ICNPQC_7C2315/6",
    origin: "ICN",
    destination: "PQC",
    route: "ICN-PQC",
    airline: "7C",
    depFlight: "7C2315",
    retFlight: "7C2316",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNPQC_ZE581_582",
    rawKey: "ICNPQC_ZE581/2",
    origin: "ICN",
    destination: "PQC",
    route: "ICN-PQC",
    airline: "ZE",
    depFlight: "ZE581",
    retFlight: "ZE582",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNPQC_TW055_056",
    rawKey: "ICNPQC_TW055/6",
    origin: "ICN",
    destination: "PQC",
    route: "ICN-PQC",
    airline: "TW",
    depFlight: "TW055",
    retFlight: "TW056",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNBKK_ZE511_512",
    rawKey: "ICNBKK_ZE511/2",
    origin: "ICN",
    destination: "BKK",
    route: "ICN-BKK",
    airline: "ZE",
    depFlight: "ZE511",
    retFlight: "ZE512",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNBKK_YP601_602",
    rawKey: "ICNBKK_YP601/2",
    origin: "ICN",
    destination: "BKK",
    route: "ICN-BKK",
    airline: "YP",
    depFlight: "YP601",
    retFlight: "YP602",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNBKK_LJ001_002",
    rawKey: "ICNBKK_LJ001/2",
    origin: "ICN",
    destination: "BKK",
    route: "ICN-BKK",
    airline: "LJ",
    depFlight: "LJ001",
    retFlight: "LJ002",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNBKK_TW101_102",
    rawKey: "ICNBKK_TW101/2",
    origin: "ICN",
    destination: "BKK",
    route: "ICN-BKK",
    airline: "TW",
    depFlight: "TW101",
    retFlight: "TW102",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNCNX_LJ027_028",
    rawKey: "ICNCNX_LJ027/8",
    origin: "ICN",
    destination: "CNX",
    route: "ICN-CNX",
    airline: "LJ",
    depFlight: "LJ027",
    retFlight: "LJ028",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNCNX_ZE517_518",
    rawKey: "ICNCNX_ZE517/8",
    origin: "ICN",
    destination: "CNX",
    route: "ICN-CNX",
    airline: "ZE",
    depFlight: "ZE517",
    retFlight: "ZE518",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "ICNCNX_7C2515_2516",
    rawKey: "ICNCNX_7C2515/6",
    origin: "ICN",
    destination: "CNX",
    route: "ICN-CNX",
    airline: "7C",
    depFlight: "7C2515",
    retFlight: "7C2516",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "PUSDAD_LJ763_764",
    rawKey: "PUSDAD_LJ763/4",
    origin: "PUS",
    destination: "DAD",
    route: "PUS-DAD",
    airline: "LJ",
    depFlight: "LJ763",
    retFlight: "LJ764",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "PUSDAD_LJ111_112",
    rawKey: "PUSDAD_LJ111/2",
    origin: "PUS",
    destination: "DAD",
    route: "PUS-DAD",
    airline: "LJ",
    depFlight: "LJ111",
    retFlight: "LJ112",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "PUSCXR_TW041_042",
    rawKey: "PUSCXR_TW041/2",
    origin: "PUS",
    destination: "CXR",
    route: "PUS-CXR",
    airline: "TW",
    depFlight: "TW041",
    retFlight: "TW042",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },  
{
    key: "PUSCXR_LJ115 _116",
    rawKey: "PUSCXR_LJ 115/6",
    origin: "PUS",
    destination: "CXR",
    route: "PUS-CXR",
    airline: "LJ",
    depFlight: "LJ115 ",
    retFlight: "LJ116 ",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "PUSBKK_LJ021_022",
    rawKey: "PUSBKK_LJ021/2",
    origin: "PUS",
    destination: "BKK",
    route: "PUS-BKK",
    airline: "LJ",
    depFlight: "LJ021",
    retFlight: "LJ022",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "PUSBKK_7C2551_2552",
    rawKey: "PUSBKK_7C2551/2",
    origin: "PUS",
    destination: "BKK",
    route: "PUS-BKK",
    airline: "7C",
    depFlight: "7C2551",
    retFlight: "7C2552",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  },
  {
    key: "PUSCNX_ZE917_918",
    rawKey: "PUSCNX_ZE917/8",
    origin: "PUS",
    destination: "CNX",
    route: "PUS-CNX",
    airline: "ZE",
    depFlight: "ZE917",
    retFlight: "ZE918",
    retDepartureTime: null,
    defaultProductDays: 5,
    enabled: true
  }
];

export default flightMasters;
